import 'package:laboratorio_3/config/config.dart';
import 'package:laboratorio_3/models/models.dart';

List<Process> processConstantList = [
  Process(
    isSelected: false,
    name: 'Spotify',
    size: 0.5,
    isDeleted: false,
    color: Palette.spotify,
  ),
  Process(
    isSelected: false,
    name: 'Zoom',
    size: 0.4,
    isDeleted: false,
    color: Palette.zoom,
  ),
  Process(
    isSelected: false,
    name: 'VS Code',
    size: 0.6,
    isDeleted: false,
    color: Palette.vsCode,
  ),
  Process(
    isSelected: false,
    name: 'Steam',
    size: 0.8,
    isDeleted: false,
    color: Palette.steam,
  ),
  Process(
    isSelected: false,
    name: 'Whatsapp',
    size: 1,
    isDeleted: false,
    color: Palette.whatsapp,
  ),
  Process(
    isSelected: false,
    name: 'NetBeans',
    size: 1.2,
    isDeleted: false,
    color: Palette.netbeans,
  ),
  Process(
    isSelected: false,
    name: 'Google Chrome',
    size: 3,
    isDeleted: false,
    color: Palette.chrome,
  ),
  Process(
    isSelected: false,
    name: 'Microsoft Teams',
    size: 1.5,
    isDeleted: false,
    color: Palette.teams,
  ),
  Process(
    isSelected: false,
    name: 'Adobe Photoshop',
    size: 1.7,
    isDeleted: false,
    color: Palette.photoshop,
  ),
  Process(
    isSelected: false,
    name: 'Adobe Reader',
    size: 1.9,
    isDeleted: false,
    color: Palette.reader,
  ),
];

List<Process> processCompleteConstantList = [
  Process(
    isSelected: false,
    name: 'Spotify',
    size: 0.5,
    isDeleted: false,
    codeSize: 0.2,
    dataSize: 0.2,
    stackSize: 0.1,
    id: '1',
    space: 0,
    color: Palette.spotify,
  ),
  Process(
    isSelected: false,
    name: 'Zoom',
    size: 0.4,
    isDeleted: false,
    codeSize: 0.1,
    dataSize: 0.1,
    stackSize: 0.2,
    id: '2',
    space: 0,
    color: Palette.zoom,
  ),
  Process(
    isSelected: false,
    name: 'VS Code',
    size: 0.6,
    isDeleted: false,
    codeSize: 0.2,
    dataSize: 0.2,
    stackSize: 0.2,
    id: '3',
    space: 0,
    color: Palette.vsCode,
  ),
  Process(
    isSelected: false,
    name: 'Steam',
    size: 0.8,
    isDeleted: false,
    codeSize: 0.3,
    dataSize: 0.3,
    stackSize: 0.2,
    id: '4',
    space: 0,
    color: Palette.steam,
  ),
  Process(
    isSelected: false,
    name: 'Whatsapp',
    size: 1,
    isDeleted: false,
    codeSize: 0.3,
    dataSize: 0.3,
    stackSize: 0.4,
    id: '5',
    color: Palette.whatsapp,
  ),
  Process(
    isSelected: false,
    name: 'NetBeans',
    size: 1.2,
    isDeleted: false,
    codeSize: 0.3,
    dataSize: 0.5,
    stackSize: 0.4,
    id: '6',
    space: 0,
    color: Palette.netbeans,
  ),
  Process(
    isSelected: false,
    name: 'Google Chrome',
    size: 3,
    isDeleted: false,
    codeSize: 1,
    dataSize: 1.5,
    stackSize: 0.5,
    id: '7',
    space: 0,
    color: Palette.chrome,
  ),
  Process(
    isSelected: false,
    name: 'Microsoft Teams',
    size: 1.5,
    isDeleted: false,
    codeSize: 0.5,
    dataSize: 0.5,
    stackSize: 0.5,
    id: '8',
    space: 0,
    color: Palette.teams,
  ),
  Process(
    isSelected: false,
    name: 'Adobe Photoshop',
    size: 1.7,
    isDeleted: false,
    codeSize: 0.4,
    dataSize: 0.3,
    stackSize: 1,
    id: '9',
    space: 0,
    color: Palette.photoshop,
  ),
  Process(
    isSelected: false,
    name: 'Adobe Reader',
    size: 1.9,
    isDeleted: false,
    codeSize: 1,
    dataSize: 0.6,
    stackSize: 0.3,
    id: '10',
    space: 0,
    color: Palette.reader,
  ),
];
