export 'static_partition/static_partition_screen.dart';
export 'variable_static_partition/variable_static_partition_screen.dart';
export 'dynamic_without_compaction_partition/dynamic_without_compaction_partition.dart';
export 'dynamic_compaction_partition/dynamic_compaction_partition.dart';